-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    date date NOT NULL,
    year integer NOT NULL,
    month_number integer NOT NULL,
    month_name character varying NOT NULL,
    day_of_month character varying NOT NULL,
    day_of_week character varying NOT NULL,
    PRIMARY KEY (date)
);

CREATE TABLE public."softcartDimCategory"
(
    category_id character varying NOT NULL,
    category_name character varying NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE public."softcartDimItem"
(
    item_id character varying NOT NULL,
    item_name character varying NOT NULL,
    item_price double precision NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE public."softcartDimCountry"
(
    country_id character varying NOT NULL,
    country_name character varying NOT NULL,
    PRIMARY KEY (country_id)
);

CREATE TABLE public."softcartFactSales"
(
    order_id character varying NOT NULL,
    item_id character varying NOT NULL,
    country_id character varying NOT NULL,
    category_id character varying NOT NULL,
    date date NOT NULL,
    PRIMARY KEY (order_id)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (category_id)
    REFERENCES public."softcartDimCategory" (category_id)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (date)
    REFERENCES public."softcartDimDate" (date)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id)
    NOT VALID;

END;